import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Connect the outputs",
  body: "Connect the cathode of each LED to the matching output pin: 1Y0, 1Y1, 1Y2 and 1Y3. An LED lights when its output pin is LOW.",
  show: [
    "bb",
    "psu",
    "dmx1",
    "w_s0",
    "w_s1",
    "w_d",
    "r_y0",
    "led_y0",
    "r_y1",
    "led_y1",
    "r_y2",
    "led_y2",
    "r_y3",
    "led_y3",
    "w_vcc_r0",
    "w_r0_led",
    "w_vcc_r1",
    "w_r1_led",
    "w_vcc_r2",
    "w_r2_led",
    "w_vcc_r3",
    "w_r3_led",
    "w_led0_y",
    "w_led1_y",
    "w_led2_y",
    "w_led3_y",
  ],
  highlight: "dmx1",
  activeInputs: { S1: 0, S0: 0, D: 1 },
  supplyVoltage: 5.0,
  ledBrightness: { led_y0: 0, led_y1: 0, led_y2: 0, led_y3: 0 },
};
