import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test with D = 1",
  body: "Set D = 1 and try any select combination. The addressed output follows D and goes HIGH, so all four outputs are HIGH and every LED is OFF. Record all rows in the observation table.",
  show: [
    "bb",
    "psu",
    "dmx1",
    "w_s0",
    "w_s1",
    "w_d",
    "r_y0",
    "led_y0",
    "r_y1",
    "led_y1",
    "r_y2",
    "led_y2",
    "r_y3",
    "led_y3",
    "w_vcc_r0",
    "w_r0_led",
    "w_vcc_r1",
    "w_r1_led",
    "w_vcc_r2",
    "w_r2_led",
    "w_vcc_r3",
    "w_r3_led",
    "w_led0_y",
    "w_led1_y",
    "w_led2_y",
    "w_led3_y",
  ],
  highlight: "led_y3",
  activeInputs: { S1: 1, S0: 1, D: 1 },
  supplyVoltage: 5.0,
  ledBrightness: { led_y0: 0, led_y1: 0, led_y2: 0, led_y3: 0 },
};
