import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Hold: S = 0, R = 0",
  body: "Return R to 0 so that S = 0 and R = 0. The flip-flop keeps its previous state: Q = 0, Q̄ = 1. The inputs are gone but the output is remembered.",
  show: [
    "bb",
    "psu",
    "nor1",
    "nor2",
    "w_fb1",
    "w_fb2",
    "w_s",
    "w_r",
    "r_q",
    "led_q",
    "r_qb",
    "led_qb",
    "w_q_r",
    "w_r_led_q",
    "w_qb_r",
    "w_r_led_qb",
    "w_gnd_q",
    "w_gnd_qb",
  ],
  highlight: "led_qb",
  activeInputs: { S: 0, R: 0 },
  supplyVoltage: 5.0,
  ledBrightness: { led_q: 0, led_qb: 1 },
};
