import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Set: S = 1, R = 0",
  body: "Set S = 1 and R = 0. Q goes to 1 and Q̄ goes to 0. The green LED glows and the yellow LED is OFF.",
  show: [
    "bb",
    "psu",
    "nor1",
    "nor2",
    "w_fb1",
    "w_fb2",
    "w_s",
    "w_r",
    "r_q",
    "led_q",
    "r_qb",
    "led_qb",
    "w_q_r",
    "w_r_led_q",
    "w_qb_r",
    "w_r_led_qb",
    "w_gnd_q",
    "w_gnd_qb",
  ],
  highlight: "led_q",
  activeInputs: { S: 1, R: 0 },
  supplyVoltage: 5.0,
  ledBrightness: { led_q: 1, led_qb: 0 },
};
